### ISSUE TITLE
录音方法，报DevicesNotFoundError

### ISSUE THREAD

**Issue by Ann-Cyq** [BenzLeung/benz-amr-recorder#11]
目前ipone上面测试一直不行， 安卓可以

**Comment by BenzLeung** [comment]
要在iPhone使用录音功能，需要 iOS 11.1+。我忘记了在 README 上注明了。请问你的 iOS 是什么版本？

**Comment by uudiv** [comment]
这个在安卓和ios兼容性是多少

**Comment by BenzLeung** [comment]
@Ann-Cyq @uudiv 已更新 README.md，注明了浏览器兼容性。
后续增加兼容性检测功能。在这个功能完成之前，本Issue将一直Open。

**Comment by DavidJone** [comment]
请问为何IOS12.4的Ipad在微信浏览器环境下amr.paly()无法正常播放语音，且不会执行播放结束的回调，同时没有报错和警告。同样在Android上却一切正常。

**Comment by BenzLeung** [comment]
已增加兼容性检测功能。使用
