### ISSUE TITLE
苹果6s上面声音播放不起

### ISSUE THREAD

**Issue by du490529204** [BenzLeung/benz-amr-recorder#12]
var amr = new BenzAMRRecorder();
          amr.initWithUrl("http://www.baidu.com/"+ data.result.voice_address).then(function() {
            amr.play();
          });
             amr.onEnded(function() {
            alert('播放完毕');
            })

**Comment by BenzLeung** [comment]
请把您这一段代码放入一个用户事件之内，例如 `click` 或 `touchstart`。参考：

 - [https://webkit.org/blog/6784/new-video-policies-for-ios/](https://webkit.org/blog/6784/new-video-policies-for-ios/)
 - [https://developers.google.com/web/updates/2017/09/autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

我将把这两个链接添加到 README 中。
