### ISSUE TITLE
与ios9 不兼容

### ISSUE THREAD

**Issue by Ann-Cyq** [BenzLeung/benz-amr-recorder#13]
与ios9 不兼容

**Comment by BenzLeung** [comment]
根据 [CanIUse](https://caniuse.com/#feat=stream)，录音功能需要 ios11+。ios10以下只能播放不能录音。[README](https://github.com/BenzLeung/benz-amr-recorder#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7) 已有说明。
