### ISSUE TITLE
请问如何在播放过程中点击按钮切换播放文件

### ISSUE THREAD

**Issue by BEIBEI123** [BenzLeung/benz-amr-recorder#14]
您好！我在做一个聊天室，可能一个音频文件还没播放结束就会点击另外一条语音，播放另外一条文件，请问如何实现？
如果我使用
amr.initWithUrl('new file url.amr').then(function() {
  amr.play();
});
amr.onEnded(function() {
  alert('播放完毕');
})
就报错说arm已存在，如果我使用

var amr = new BenzAMRRecorder();
amr.initWithUrl('path/to/voice.amr').then(function() {
  amr.play();
});
amr.onEnded(function() {
  alert('播放完毕');
})
重新new 实例化一个，就提示arm不存在，好像new 下一行不能紧接着使用initWithUrl方法，请问如何处理比较好？能不能我个changeUrl方法呢

**Comment by BenzLeung** [comment]
@BEIBEI123 
```
好像new 下一行不能紧接着使用initWithUrl方法
```
本项目的 [demo ](https://benzleung.github.io/benz-amr-recorder/demo.html) 就是 new 之后马上 initWithUrl 的，请打开并参阅 demo.html 的源代码。

对于聊天室之类的应用，建议每条语音都new一个实例，并存储语音按钮和实例对象的关联。点击播放时只调用 play() 即可。

```javascript
// 以下是伪代码，旨在会意，请不要不经修改就直接照搬
var voiceList = [];
function newVoice() {
  var n = voiceList.length;
  voiceList[n] =  new BenzAMRRecorder();
  // init 完毕之前禁止点击播放按钮
  playBtn[n].disabled = true;
  voiceList[n].initWithUrl('path/to/voice.amr').then(function() {
    playBtn[n].disabled = false;
  };
  playBtn[n].onclick = function () {
    playVoice(n);
  }
}
function playVoice(index) {
  voiceList[i].play();
}
```
