### ISSUE TITLE
小程序嵌套页面后不能播放

### ISSUE THREAD

**Issue by zhibo59** [BenzLeung/benz-amr-recorder#15]
求教，h5页面可以正常解码播放，但是小程序嵌套这个h5后就不能播放了，谁能帮忙分析下是什么原因

**Comment by BenzLeung** [comment]
我没有小程序webview的环境，因此也暂时没有针对小程序webview做测试。
谷歌看了下，小程序webview并没有限制h5原生音频，但是它似乎限制了访问资源的域名，并且限制了必须使用https访问（不能http）。
@zhibo59 建议查看webview在播放时是否有网页报错，若有，请截图或复制回帖。
