### ISSUE TITLE
最小化文件BenzAMRRecorder.min.js无法正常使用

### ISSUE THREAD

**Issue by nkjackzhang** [BenzLeung/benz-amr-recorder#16]
提示this.te 不是个函数，检查了min文件发现，是把_playEmpty()函数替换成了te，但是_defineProperty仍然注册为_playEmpty，所以报错。
另外我尝试把this.te手动替换成this._playEmpty，这个错误就跳过去了，但是仍然有其他报错，所以这个min文件根本无法运行，能否重新打包？

**Comment by BenzLeung** [comment]
@nkjackzhang 已修复于 v1.0.16。
感谢反馈。

**Comment by nkjackzhang** [comment]
确实已经修复了，谢谢。
