### ISSUE TITLE
请问加载amr后的_samples怎么存储或者转换成MP3

### ISSUE THREAD

**Issue by xwbz2017** [BenzLeung/benz-amr-recorder#2]
rt.
后端需要MP3格式，MP3兼容性好。。
然后现在就有个很尴尬的问题：其他插件不支持amr，这个插件不支持MP3（是不是打开方式不对）
求助~

**Comment by BenzLeung** [comment]
本项目只支持MP3转换成AMR，其中MP3需要浏览器的 <audio> 原生支持。若需要把音频转换成MP3，你需要多加一个MP3的编码库。[lame.js](https://github.com/ispikit/lame.js) 或 [libmp3lame-js](https://github.com/akrennmair/libmp3lame-js) 了解一下？

**Comment by xwbz2017** [comment]
@BenzLeung 额这些插件都挺大的。我之前尝试用这个 [lamejs](https://github.com/zhuker/lamejs) 转换 ，不过数据格式不兼容。。。我还是用 [jave](https://www.cnblogs.com/wqh17/p/6872880.html) 吧，直接AMR转MP3，如果能成功的话:)
