### ISSUE TITLE
ios9不兼容

### ISSUE THREAD

**Issue by Ecareyu** [BenzLeung/benz-amr-recorder#22]
大佬， ios9这个插件会引起js加载的时候就报错
报这个错
SyntaxError: Unexpected identifier 'ctx'

我们开发的时候没有使用里面的录音功能，录音我们用的是微信的sdk，我们只用了里面的amr读取播放，大佬，能不能将功能拆分开哦？

**Comment by Ecareyu** [comment]
https://stackoverflow.com/questions/34636737/unexpected-use-of-reserved-word-let-in-strict-mode

**Comment by BenzLeung** [comment]
ios9 的问题已经修复于版本1.1.1。
amr编码解码器来自于一位真·大佬，无法拆分。如果只是把录音功能拆开，js体积只能减少几KB，这对于本来就500KB的js来说实在微不足道。

**Comment by Ecareyu** [comment]
大佬，是不是还没上npm，我这更新还是1.1.0

**Comment by BenzLeung** [comment]
现在上npm了。

**Comment by Ecareyu** [comment]
幸苦大佬了👍
