### ISSUE TITLE
vue使用标签引用法不生效

### ISSUE THREAD

**Issue by Mrdouhua** [BenzLeung/benz-amr-recorder#23]
![image](https://user-images.githubusercontent.com/17821353/66824674-51913f00-ef7b-11e9-8942-5f9615fc72de.png)
1，<script type="text/javascript" src="./BenzAMRRecorder.min.js"></script>这种方式引入后，无法使用new BenzAMRRecorder()
2，但是var BenzAMRRecorder = require('benz-amr-recorder')这种方式可以正常使用
3，另外，非vue项目，在原生html页面使用script标签引用可以正常使用

请大佬们指点迷津

**Comment by BenzLeung** [comment]
看起来你的截图是一个 *.vue 文件。
*.vue 文件中的 <script> 与 *.html 的 <script> 是不一样的。每个*.vue 文件只能有1个<script>。
如果你一定要使用<script>引入js，请使用谷歌或百度寻找解决方法。
