### ISSUE TITLE
不同源的amr格式音频不能播放吗？

### ISSUE THREAD

**Issue by Clareforwyy** [BenzLeung/benz-amr-recorder#24]
项目中的音频是存在别的服务器上的，使用这个会报跨域的错误

**Comment by BenzLeung** [comment]
@Clareforwyy 服务器回应 `Access-Control-Allow-Origin`, `Access-Control-Allow-Credentials`, `Access-Control-Expose-Headers` 这些相关请求header。每种服务器语言的设置方法都不同，详情请咨询 Google。
