### ISSUE TITLE
benz-amr-recorder如何重新初始化

### ISSUE THREAD

**Issue by LoverFancy** [BenzLeung/benz-amr-recorder#30]
有这样简单的需求，通过不同的url播放不同的arm文件，但是benz-amr-recorder已经痛殴url初始化了。无法再次初始化，不能实现类似音乐播放切换音乐的效果

**Comment by BenzLeung** [comment]
@LoverFancy 已经初始化过的对象用完即弃，切换音频只要重新new一个新对象即可。new多个对象还可以同时混音播放。旧的对象只要没有变量引用就会被自动垃圾回收，不会有内存泄漏的。
