### ISSUE TITLE
播放音乐切换控制问题

### ISSUE THREAD

**Issue by LoverFancy** [BenzLeung/benz-amr-recorder#31]
@BenzLeung 感谢回复，音乐切换有两个细节问题
场景是这样的：我有多个播放按钮是异步获取音乐的url, 但是我只能播放某一个音乐：
1. 点击当前音乐的播放按钮可以控制播放和暂停；
2.点击别的音乐播放按钮需要停止之前的音乐并播放当前的音乐。
直接new 对象的方式无法实现相互控制。

**Comment by BenzLeung** [comment]
@LoverFancy 对于第2点，只需要先停止当前音乐，然后抛弃当前音乐的对象，重新new对象，然后播放。
