### ISSUE TITLE
微信amr 解码失败

### ISSUE THREAD

**Issue by wanhua1993** [BenzLeung/benz-amr-recorder#38]

**Comment by wanhua1993** [comment]
微信语音上传到oss后 解码这个地址 会失败

**Comment by ly616187030** [comment]
同问，amr上传到oss上，直接播放远端地址，无法播放，默认带上了当前域名

**Comment by BenzLeung** [comment]
@wanhua1993 @ly616187030 你们先试试能否直接下载oss上的amr文件。这无法播放的原因有很多种可能，例如微信官方会屏蔽阿里云的OSS，或者OSS端有跨域限制等等
