### ISSUE TITLE
请问录音的类型，最后录制完成的格式，只能是amr吗？支持转换成aac吗？

### ISSUE THREAD

**Issue by Change-TheWorld** [BenzLeung/benz-amr-recorder#40]
如题，我看最终可以转换成 amr 或者mp3, 那么 ，aac格式的支持吗？

**Comment by BenzLeung** [comment]
本项目只集成了 amr-nb 的编码+解码库，因此只能支持 amr <-> pcm 这两个格式互转。现代浏览器都原生支持 mp3 和 aac 的解码，但是不支持 mp3 和 aac **编码**。因此，本项目支持 mp3、aac **单向**转换成 amr-nb 格式（用浏览器原生方法把 mp3/aac 解码成 pcm 然后用本项目编码成 amr），但是不支持 amr 转换成 mp3/aac 等其他格式。

对于js前端，目前我只见过 mp3 编码器，暂时没有见过能用 js 来编码 aac 格式的。原因也不难想象，不像 amr 只有 nb/wb 两种格式，aac 可是多达9种格式……
