### ISSUE TITLE
手机上的录音文件转码失败

### ISSUE THREAD

**Issue by lmr520** [BenzLeung/benz-amr-recorder#41]
手机上的录音文件无法播放
53:1 Uncaught (in promise) DOMException: Unable to decode audio data
BenzAMRRecorder.js:30746 Uncaught (in promise) Error: Failed to decode.

[该录音为系统自动通话录音

**Comment by BenzLeung** [comment]
确认录音文件是不是amr-nb格式？

**Comment by lmr520** [comment]
是.amr格式
[183 3486 9317_20200713225440.amr.zip](https://github.com/BenzLeung/benz-amr-recorder/files/4992027/183.3486.9317_20200713225440.amr.zip)
你帮我看看

**Comment by BenzLeung** [comment]
你的amr文件是 amr-wb 格式，不是 amr-nb，我暂时没空实现 amr-wb，你可以考虑加上这个库： https://github.com/sblandford/amrwb-js 。

**Comment by lmr520** [comment]
好的 谢谢，我看你这库可以的，有空的时候可以加一下

**Comment by BenzLeung** [comment]
嗯，感谢支持~ 最近忙项目，以后我会考虑的

**Comment by liyaan** [comment]
我的是amr-nb不能播放
