### ISSUE TITLE
可以提供一些属性， 内容是解析后的mp3格式吗？

### ISSUE THREAD

**Issue by dongshuangshuang** [BenzLeung/benz-amr-recorder#43]

**Comment by BenzLeung** [comment]
@dongshuangshuang 没有懂你的意思，是想要把音频转换为mp3吗？

**Comment by imsole** [comment]
> @dongshuangshuang 没有懂你的意思，是想要把音频转换为mp3吗？

他应该是那个意思，吧录音转换为mp3格式

**Comment by BenzLeung** [comment]
@dongshuangshuang @imsole 我这个库没有集成mp3编码器，无法转换为mp3。要转换为mp3格式你们需要自己寻找编码器，例如可以了解一下 lamejs： https://github.com/zhuker/lamejs 。注意事项：

1. 如果想要把录音所得的音频转换成mp3，你需要自行实现录音功能。
2. 如果想要把 amr 转换成 mp3，需要注意采样率的转换，amr固定为8000，mp3支持22050或44100等。
3. lamejs 是 LGPL 协议的。

想要更简单的话，也可以了解一下 https://github.com/xiangyuecn/Recorder 。这个库支持多种格式互相转换，包括mp3，其中amr部分引用 了我这里的 amrnb.js 的，我看着还可以。
