### ISSUE TITLE
可以提供一个销毁组件实例的方法么？

### ISSUE THREAD

**Issue by shuashuai** [BenzLeung/benz-amr-recorder#45]
场景：双方聊天多个语音，每次播放都只能新创建一个，这样会造成同时有多个语音在播放

**Comment by BenzLeung** [comment]
只要调用 pause() 或者 stop() 停止播放，然后确保没有任何变量引用实例，然后坐等浏览器的垃圾回收器回收实例内存就好了。换言之，你完全可以把 stop() 当成销毁实例的方法来用。
