### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by sagexy** [BenzLeung/benz-amr-recorder#47]
Chrome浏览器报警告The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

![image](https://user-images.githubusercontent.com/4734448/104674279-531d5a00-571e-11eb-8674-57ff61886c36.png)

**Comment by BenzLeung** [comment]
已修复于 v1.1.3
