### ISSUE TITLE
小程序无法使用

### ISSUE THREAD

**Issue by sixsixsix516** [BenzLeung/benz-amr-recorder#49]
![image](https://user-images.githubusercontent.com/45815935/107140610-2693e100-695e-11eb-8560-13c4c31c1efd.png)
![image](https://user-images.githubusercontent.com/45815935/107140622-41665580-695e-11eb-8f73-2c9570aef92f.png)
如图 New对象的时候报错

代码是  let soundInstance = new BenzAMRRecorder();
然后报错
TypeError: Cannot read property 'AudioContext' of undefined
    at BenzAMRRecorder.js?t=wechat&s=1612677238981&v=6bc5d1f35f8f610d9ca7773c0ee5478b:290
    at BenzAMRRecorder.js?t=wechat&s=1612677238981&v=6bc5d1f35f8f610d9ca7773c0ee5478b:2
    at BenzAMRRecorder.js?t=wechat&s=1612677238981&v=6bc5d1f35f8f610d9ca7773c0ee5478b:5
    at require (VM5786 WAService.js:2)
    at VM5786 WAService.js:2
    at index.js? [sm]:6
    at require (VM5786 WAService.js:2)
    at <anonymous>:996:9
    at doWhenAllScriptLoaded (<anonymous>:1175:21)
    at Object.scriptLoaded (<anonymous>:1195:5)

**Comment by BenzLeung** [comment]
@sixsixsix516 你好，本项目并不是给小程序使用的。小程序不支持 Web Audio API （甚至不支持 js 的 window 对象）。如果需要在小程序中播放amr，可以直接用小程序提供的音频能力接口。（不过我刚刚粗略查了下，好像只有Android版微信才支持amr）

总之，本项目就不是给小程序使用的……
