### ISSUE TITLE
ios 无法播放amr格式的语音

### ISSUE THREAD

**Issue by AgainZhao** [BenzLeung/benz-amr-recorder#5]

**Comment by BenzLeung** [comment]
@AgainZhao ios10-12运行Demo是正常的，可否提供更多信息？例如语音文件的来源，或者给我提供语音文件？

**Comment by Ecareyu** [comment]
> @AgainZhao ios10-12运行Demo是正常的，可否提供更多信息？例如语音文件的来源，或者给我提供语音文件？

iphone6s ios12.3.1 微信7.0.5 就你的demo，播放不了音频.
