### ISSUE TITLE
如果播amr 正播放呢，我把这个页面销毁了，音频还在播放bug

### ISSUE THREAD

**Issue by crownclownwl** [BenzLeung/benz-amr-recorder#50]
如果播amr 正播放呢，我把这个页面销毁了，音频还在播放，除非我F5 刷新页面，
有没有别的处理方式，比如可以在 页面关闭时候调用amr 对象的 destroy() 方法类似的逻辑呢
或者有别的方法吗？

```jsx
  // 我先定义了一个这个，用来接受 amr 对象
  const audioRef = useRef(); //audio标签Ref

  // 定义 amr 并 赋值给 audioRef.current
  const armOptions = {
      src: audioInfo.src,
      isloop: loop,
  };
  const amr = initArmObj(callBack, armOptions);
  audioRef.current = amr;

  // 当页面销毁时候手动置空
 
  useEffect(() => {
        return (() => {
            // 如果是amr 类型文件，存在一直播放bug
            if (ext === 'amr') {
                audioRef.current.stop();
            }

            // 销毁音频组件
            audioRef.current = null;
        });
    }, [ext]);
 
 
```

**Comment by BenzLeung** [comment]
其实我没有看懂你贴的代码，代码里没有调用到本项目……你是怎么调用本项目的？

**Comment by crownclownwl** [comment]
`jsx
   import BenzAMRRecorder from 'benz-amr-recorder';

export const initArmObj = (initWithUrlCallBack: Function, options: any) => {
    const amr = new BenzAMRRecorder();
    // amr初始化
    amr.initWithUrl(options.src).then(function () {
        if (typeof initWithUrlCallBack === 'function') {
            initWithUrlCallBack();
        }
    });
    // amr结束播放
    amr.onEnded(function () {
        if (options.isloop) {
            amr.play();
        }
    });

    return amr;
};

`

**Comment by crownclownwl** [comment]
我把 arm播放器放到了 antd 的 modal 弹出框里了，当弹出框 关闭时候，还能听见这个播放器在播放音乐
应该是因为 arm 实例没有销毁导致的吧

**Comment by crownclownwl** [comment]
是因为 我手动调用了 play() 导致的
```jsx
   // amr结束播放
    amr.onEnded(function () {
        debugger
        if (options.isloop) {
            // amr.play();
        }
    });
```

**Comment by crownclownwl** [comment]
我追加了一个 特殊变量 来 配合 监听
```tsx
  // amr结束播放
    amr.onEnded(function () {
        if (!amr['_isDestory'] && options.isloop) {
            amr.play();
        }
    });
```
