### ISSUE TITLE
webpack3.10打包会报莫名的错误

### ISSUE THREAD

**Issue by mybedhome** [BenzLeung/benz-amr-recorder#7]
webpack3.10打包后会bao报莫名的错误，且导致公共chunk没法压缩成一行。
![image](https://user-images.githubusercontent.com/6857151/52624227-38665900-2ee9-11e9-8ce2-0770870178a5.png)

**Comment by BenzLeung** [comment]
@mybedhome 按理说只要兼容了 CommonJS 标准的 package 就能使用 Webpack 打包。我觉得这与本项目无关。建议你再次检查 Webpack 的 config，或者升级 Webpack 到 v3.12 再试试。另外因为现代浏览器都可以直接解释es6的代码，所以本项目的入口文件保留了一些es6的语法。或者你也可以对本项目加入babel之类的loader试试。
