### ISSUE TITLE
DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data

### ISSUE THREAD

**Issue by shuiRong** [BenzLeung/benz-amr-recorder#70]
Error: Failed to decode.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/16076993/176345561-16ff135b-959d-4ba4-b47c-b1ba55c31e92.png">

用我这个AMR文件在DEMO页面测试时，报错。

测试文件附在这里了，下载后手动去掉后缀`.txt`

[1656413961345.amr.txt](https://github.com/BenzLeung/benz-amr-recorder/files/9007042/1656413961345.amr.txt)

（另外，为了后续Google搜来的用户。这个项目的DEMO页面测试时，我发现能正常播放。）
https://github.com/sblandford/amrwb-js

**Comment by BenzLeung** [comment]
本项目仅支持 amr-nb 格式，不支持 amr-wb。

如有需求，可以试试此git友的fork版本： https://github.com/AcoWaves/benz-amr-recorder
