### ISSUE TITLE
可以考虑支持流式录制播放吗

### ISSUE THREAD

**Issue by ocean2811** [BenzLeung/benz-amr-recorder#72]
如题,能否支持在录制时,每隔指定时间就抛出一次buffer用于上传,即边录边上传;还有在播放时,实施追加下载的amr流到待播放buffer中,实现边下载边播放

**Comment by BenzLeung** [comment]
这个有难度，我没有试过amr文件只下载一半能不能正常解码，如果能解码就可以。至于分块上传，也许只能上传很多个amr文件，然后服务器还不能简单地把amr文件合并起来，需要解码成pcm后合并。
