### ISSUE TITLE
浏览器里 测试demo.html报错，播放.amr文件

### ISSUE THREAD

**Issue by zxingdream** [BenzLeung/benz-amr-recorder#75]
![image](https://user-images.githubusercontent.com/12619680/206678544-a4837f09-918f-4936-932d-88bdabfea016.png)

**Comment by BenzLeung** [comment]
你自己的amr文件很可能不是 amr-nb 格式。demo.html 没有捕获这种错误。实际应用中你需要给 `initWithXXX` 写 `catch(...)`。

```
amr.initWithBlob(file).then(/*...*/).catch(/*....*/)
```

**Comment by zxingdream** [comment]
![image](https://user-images.githubusercontent.com/12619680/210955739-c6cf043d-d22e-43e5-a798-d7859e800eae.png)

标准的手机通话录音文件啊，我用播放器是可以正常播放的，如下图
![image](https://user-images.githubusercontent.com/12619680/210955860-52cfd1c1-b213-4aca-9fa7-7b84f96f69d2.png)
