### ISSUE TITLE
手机通话录音的amr文件好像就无法播放？

### ISSUE THREAD

**Issue by zxingdream** [BenzLeung/benz-amr-recorder#77]
![image](https://user-images.githubusercontent.com/12619680/210956165-fba1c439-dca9-410c-b53a-034590c24443.png)
用播放器是可以正常播放的，如下图
![image](https://user-images.githubusercontent.com/12619680/210956408-f268371c-4b1c-4aed-8ac8-517c80c45b43.png)

**Comment by BenzLeung** [comment]
你的播放器截图有标示“16khz”，不支持这个格式。请阅读readme最后的faq。
