### ISSUE TITLE
采样率现在永远是8000，可以是其他配置吗？比如16000

### ISSUE THREAD

**Issue by fakerName** [BenzLeung/benz-amr-recorder#8]

**Comment by BenzLeung** [comment]
AMR-NB 格式的音频固定采样率是8000，参见[维基百科](https://zh.wikipedia.org/wiki/%E8%87%AA%E9%80%82%E5%BA%94%E5%A4%9A%E9%80%9F%E7%8E%87%E9%9F%B3%E9%A2%91%E5%8E%8B%E7%BC%A9#%E7%89%B9%E7%82%B9)。

（另有一种 AMR-WB 的格式，固定采样率是16000，但是使用场景不多，我暂时不打算研究和支持。）

**Comment by zxingdream** [comment]
> 

终于发现问题了，原来手机通话录音产生的文件格式是AMR-WB 16000的 ，不打算支撑了 ？
